/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoldersIndexRouteImport } from './routes/folders.index'
import { Route as FoldersFolderIndexRouteImport } from './routes/folders.$folder.index'
import { Route as FoldersFolderWriteRouteImport } from './routes/folders.$folder.write'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersIndexRoute = FoldersIndexRouteImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderIndexRoute = FoldersFolderIndexRouteImport.update({
  id: '/folders/$folder/',
  path: '/folders/$folder/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderWriteRoute = FoldersFolderWriteRouteImport.update({
  id: '/folders/$folder/write',
  path: '/folders/$folder/write',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/folders/': typeof FoldersIndexRoute
  '/folders/$folder/write': typeof FoldersFolderWriteRoute
  '/folders/$folder/': typeof FoldersFolderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/folders': typeof FoldersIndexRoute
  '/folders/$folder/write': typeof FoldersFolderWriteRoute
  '/folders/$folder': typeof FoldersFolderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/folders/': typeof FoldersIndexRoute
  '/folders/$folder/write': typeof FoldersFolderWriteRoute
  '/folders/$folder/': typeof FoldersFolderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/folders/' | '/folders/$folder/write' | '/folders/$folder/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/folders' | '/folders/$folder/write' | '/folders/$folder'
  id:
    | '__root__'
    | '/'
    | '/folders/'
    | '/folders/$folder/write'
    | '/folders/$folder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoldersIndexRoute: typeof FoldersIndexRoute
  FoldersFolderWriteRoute: typeof FoldersFolderWriteRoute
  FoldersFolderIndexRoute: typeof FoldersFolderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/': {
      id: '/folders/'
      path: '/folders'
      fullPath: '/folders/'
      preLoaderRoute: typeof FoldersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folder/': {
      id: '/folders/$folder/'
      path: '/folders/$folder'
      fullPath: '/folders/$folder/'
      preLoaderRoute: typeof FoldersFolderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folder/write': {
      id: '/folders/$folder/write'
      path: '/folders/$folder/write'
      fullPath: '/folders/$folder/write'
      preLoaderRoute: typeof FoldersFolderWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoldersIndexRoute: FoldersIndexRoute,
  FoldersFolderWriteRoute: FoldersFolderWriteRoute,
  FoldersFolderIndexRoute: FoldersFolderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
